# Generated by Django 4.1 on 2023-05-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcprice',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
